name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: "$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: "ðŸš¨ Major Release ðŸš¨"
    labels:
      - "major-change"
  - title: "ðŸš¨ Breaking changes"
    labels:
      - "breaking-change"
  - title: "âœ¨ New features"
    labels:
      - "new-feature"
  - title: "ðŸ› Bug fixes"
    labels:
      - "bugfix"
  - title: "ðŸš€ Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "ðŸ§° Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "ðŸ“š Documentation"
    labels:
      - "documentation"
  - title: "â¬†ï¸ Dependency updates"
    collapse-after: 5
    labels:
      - "dependencies"
  - title: "ðŸš¨ðŸš¨ Security Fixes ðŸš¨ðŸš¨"
    labels:
      - "security"

exclude-labels:
  - "sync"

version-resolver:
  major:
    labels:
      - "major-change"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "performance"
      - "refactor"
      - "security"
  default: patch
no-changes-template: '- No changes'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/Diondk/ultimatesensor-mini/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

   _To receive a notification on new releases, click on **Watch** > **Custom** > **Releases** on the top._

   _Be sure to ðŸŒŸ this repository for updates! Its a hobby project . Flash it go to the link https://web.esphome.io/._

  ## Contributors

  $CONTRIBUTORS
