# UltimateSensor Basic Configuration
# This configuration excludes the Particulate Matter (PM) sensor.
# Use this file if your device does not include the PM/fine dust sensor.

# Name of device
substitutions:
  device_name: ultimatesensor-mini
  friendly_name: "UltimateSensor Mini"
  ultimatesensor_mini_software_version: "1.3"
  ultimatesensor_mini_hardware_version: "V1-Basic"
  wifi_fast_connect: "true"
  update_manifest_url: "https://smarthomeshop.github.io/ultimatesensor-mini/ultimatesensor-mini-basic-manifest.json"

packages:
  common: !include ultimatesensor-mini-common.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/ultimatesensor-mini/ultimatesensor-mini-v1/ultimatesensor-mini-basic.yaml@main
  import_full_config: false
