# UltimateSensor Complete Configuration
# This configuration includes settings for all sensors, including the Particulate Matter (PM) sensor.
# Use this file if your device includes the PM/fine dust measurement capability.

# Name of device
substitutions:
  device_name: ultimatesensor-mini
  friendly_name: "UltimateSensor Mini"
  ultimatesensor_mini_hardware_version: "V1-Complete"
  wifi_fast_connect: "true"
  update_manifest_url: "https://smarthomeshop.github.io/ultimatesensor-mini/ultimatesensor-mini-complete-manifest.json"
  basic_manifest_url: "https://smarthomeshop.github.io/ultimatesensor-mini/ultimatesensor-mini-basic-manifest.json"
  complete_manifest_url: "https://smarthomeshop.github.io/ultimatesensor-mini/ultimatesensor-mini-complete-manifest.json"
  basic_cloud_manifest_url: "https://smarthomeshop.github.io/ultimatesensor-mini/ultimatesensor-mini-basic-cloud-manifest.json"
  complete_cloud_manifest_url: "https://smarthomeshop.github.io/ultimatesensor-mini/ultimatesensor-mini-complete-cloud-manifest.json"
  default_network: "WiFi Complete (local)"
  cloud_enabled: "false"

packages:
  common: !include ultimatesensor-mini-common.yaml
  sps30: !include sps30.yaml

dashboard_import:
  package_import_url: github://smarthomeshop/ultimatesensor-mini/ultimatesensor-mini-v1/ultimatesensor-mini-complete.yaml@main
  import_full_config: false
