name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        file:
          - ultimatesensor-mini-v1/ultimatesensor-mini-basic.yaml
          - ultimatesensor-mini-v1/ultimatesensor-mini-complete.yaml

        esphome-version:
          - latest
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v4.0.4
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
