name: Compile ESPHome Binary

on:
  push:
    paths:
      - 'ultimatesensor-mini-v1/**.yaml'  # Trigger only on changes to YAML files
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13

    - name: Verify Python Version
      run: python --version

    - name: Clean Python Environment
      run: |
        python -m pip uninstall -y pip
        python -m ensurepip
        python -m pip install --upgrade pip setuptools

    - name: Install ESPHome
      run: pip install esphome==2024.2.1  # Use specific ESPHome version

    - name: Compile ESPHome Binary
      run: esphome compile ultimatesensor-mini-v1/my_device.yaml

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: esphome-my_device
        path: ultimatesensor-mini-v1/build/my_device/.pioenvs/my_device/firmware.bin
