name: Compile ESPHome Binaries

on:
  push:
    paths:
      - 'ultimatesensor-mini-basic.yaml'
      - 'ultimatesensor-mini-complete.yaml'  # Trigger only on changes to these YAML files
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-basic:
    name: Build Basic Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build ESPHome Firmware (Basic)
      uses: esphome/build-action@v2
      with:
        configuration: ultimatesensor-mini-basic.yaml

    - name: Upload Firmware Binary (Basic)
      uses: actions/upload-artifact@v3
      with:
        name: firmware-basic
        path: .esphome/build/ultimatesensor-mini-basic/.pioenvs/ultimatesensor-mini-basic/firmware.bin

  build-complete:
    name: Build Complete Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build ESPHome Firmware (Complete)
      uses: esphome/build-action@v2
      with:
        configuration: ultimatesensor-mini-complete.yaml

    - name: Upload Firmware Binary (Complete)
      uses: actions/upload-artifact@v3
      with:
        name: firmware-complete
        path: .esphome/build/ultimatesensor-mini-complete/.pioenvs/ultimatesensor-mini-complete/firmware.bin
