name: Compile ESPHome Binaries

on:
  push:
    paths:
      - 'ultimatesensor-mini-v1/ultimatesensor-mini-basic.yaml'
      - 'ultimatesensor-mini-v1/ultimatesensor-mini-complete.yaml'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-basic:
    name: Build Basic Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build ESPHome Firmware (Basic)
      uses: esphome/build-action@v2
      with:
        yaml_file: ultimatesensor-mini-v1/ultimatesensor-mini-basic.yaml

    - name: Move and Rename Firmware (Basic)
      run: |
        # Move the firmware to the desired directory and rename it
        mkdir -p ultimatesensor-mini-v1/bin
        mv .esphome/build/ultimatesensor-mini-v1/ultimatesensor-mini-basic/.pioenvs/ultimatesensor-mini-basic/firmware.bin ultimatesensor-mini-v1/bin/ultimatesensor-mini-basic-v1.1.bin

    - name: Upload Firmware Binary (Basic)
      uses: actions/upload-artifact@v3
      with:
        name: firmware-basic
        path: ultimatesensor-mini-v1/bin/ultimatesensor-mini-basic-v1.1.bin

  build-complete:
    name: Build Complete Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build ESPHome Firmware (Complete)
      uses: esphome/build-action@v2
      with:
        yaml_file: ultimatesensor-mini-v1/ultimatesensor-mini-complete.yaml

    - name: Move and Rename Firmware (Complete)
      run: |
        # Move the firmware to the desired directory and rename it
        mkdir -p ultimatesensor-mini-v1/bin
        mv .esphome/build/ultimatesensor-mini-v1/ultimatesensor-mini-complete/.pioenvs/ultimatesensor-mini-complete/firmware.bin ultimatesensor-mini-v1/bin/ultimatesensor-mini-complete-v1.1.bin

    - name: Upload Firmware Binary (Complete)
      uses: actions/upload-artifact@v3
      with:
        name: firmware-complete
        path: ultimatesensor-mini-v1/bin/ultimatesensor-mini-complete-v1.1.bin
