name: Compile ESPHome Binary

on:
  push:
    paths:
      - 'ultimatesensor-mini-v1/**.yaml'  # Trigger only on changes to YAML files
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install ESPHome
      run: |
        python -m pip install --upgrade pip
        pip install esphome

    - name: Compile ESPHome Binary (Basic)
      uses: esphome/build-action@v1
      with:
        yaml_file: 'ultimatesensor-mini-v1/ultimatesensor-mini-basic.yaml'

    - name: Compile ESPHome Binary (Complete)
      uses: esphome/build-action@v1
      with:
        yaml_file: 'ultimatesensor-mini-v1/ultimatesensor-mini-complete.yaml'

    - name: Move and Rename Firmware (Basic)
      run: |
        mkdir -p ultimatesensor-mini-v1/bin
        mv .esphome/build/ultimatesensor-mini-v1/.pioenvs/ultimatesensor-mini/firmware.bin ultimatesensor-mini-v1/bin/ultimatesensor-mini-basic-v1.1.bin

    - name: Move and Rename Firmware (Complete)
      run: |
        mkdir -p ultimatesensor-mini-v1/bin
        mv .esphome/build/ultimatesensor-mini-v1/.pioenvs/ultimatesensor-mini/firmware.bin ultimatesensor-mini-v1/bin/ultimatesensor-mini-complete-v1.1.bin

    - name: Upload Artifact (Basic)
      uses: actions/upload-artifact@v3
      with:
        name: esphome-basic-firmware
        path: ultimatesensor-mini-v1/bin/ultimatesensor-mini-basic-v1.1.bin

    - name: Upload Artifact (Complete)
      uses: actions/upload-artifact@v3
      with:
        name: esphome-complete-firmware
        path: ultimatesensor-mini-v1/bin/ultimatesensor-mini-complete-v1.1.bin
